import Head from "next/head";
import { useEffect } from "react";
import About from "../components/About";
import Banner from "../components/Banner";
import Banner2 from "../components/Banner2";
import Experience from "../components/Experience";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Menu from "../components/Menu";
import OpenHour from "../components/OpenHour";
import Service from "../components/Service";
import VisitUs from "../components/VisitUs";
import { urlFor } from "../sanity";
import {
  fetchBanner,
  fetchCafeDetail,
  fetchCategory,
  fetchExperience,
  fetchGallery,
  fetchHome,
  fetchMenu,
  fetchProducts,
  fetchService,
  fetchSocial,
  fetchVisitUs,
} from "../utils/fetchSanity";

export default function Home({
  cafe,
  home,
  menu,
  products,
  category,
  banner,
  gallery,
  experience,
  visitUs,
  service,
  social,
}) {
  function scrollActive() {
    const sections = document.querySelectorAll("section[id]");

    const scrollY = window.pageYOffset;

    sections.forEach((current) => {
      const sectionHeight = current.offsetHeight;
      let sectionTop = current.offsetTop - 300;
      let sectionId = current.getAttribute("id");

      if (scrollY > sectionTop && scrollY <= sectionTop + sectionHeight) {
        document
          .querySelector(".nav__menu a[href*=" + sectionId + "]")
          .classList.add("active-link");
      } else {
        document
          .querySelector(".nav__menu a[href*=" + sectionId + "]")
          .classList.remove("active-link");
      }
    });
  }
  useEffect(() => {
    window.addEventListener("scroll", scrollActive);
  });

  return (
    <div>
      <Head>
        <title>{cafe.titleWeb ?? "Cafe"}</title>
        <meta
          name="description"
          content={cafe.welcomeTitle ?? "Generated by create next app"}
        />
        <link
          rel="icon"
          href={"https://cdn.icon-icons.com/images/icon-icons.svg"}
        />
      </Head>
      <Header cafe={cafe} social={social} />
      <main>
        <Banner home={home} />
        <Service service={service} />
        <About cafe={cafe} />
        <Banner2 banner={banner} />
        <Menu menu={menu} category={category} products={products} />
        <OpenHour cafe={cafe} />
      </main>
      <Experience experience={experience} />
      <VisitUs visitUs={visitUs} />
      <Footer cafe={cafe} gallery={gallery} social={social} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const cafe = await fetchCafeDetail();
  const home = await fetchHome();
  const menu = await fetchMenu();
  const products = await fetchProducts();
  const category = await fetchCategory();
  const banner = await fetchBanner();
  const gallery = await fetchGallery();
  const experience = await fetchExperience();
  const visitUs = await fetchVisitUs();
  const service = await fetchService();
  const social = await fetchSocial();
  return {
    props: {
      cafe,
      home,
      menu,
      products,
      category,
      banner,
      gallery,
      experience,
      visitUs,
      service,
      social,
    },
  };
};
